### ISSUE TITLE
Default environment is always installed when calling `pixi run`

### ISSUE THREAD

**Issue by borchero** [prefix-dev/setup-pixi#102]
While this might be expected behavior, it caught me by surprise that

```
- name: Setup pixi
  uses: prefix-dev/setup-pixi@v0.6.0
  with:
    environments: test
- name: Run tests
  run: pixi run pytest
  shell: pixi run bash -e {0}
```

installs the `default` environment along with the `test` environment once `pixi run` is called.

Would it be feasible for `pixi run` to use the previously installed environment?

**Comment by pavelzw** [comment]
I'm not sure I understand your use case. Why are you not doing

```yml
- name: Setup pixi
  uses: prefix-dev/setup-pixi@v0.6.0
  with:
    environments: test
- name: Run tests
  run: pixi run -e test pytest
```

i.e. without `shell:...` and with `-e test`?

> Would it be feasible for pixi run to use the previously installed environment?

This would be a bit awkward since this would change the way pixi behaves just by the environments that are installed. IMO the environments should be thought of as ephermal and not relevant to how `pixi run` behaves.
