### ISSUE TITLE
Using setup-pixi twice in a workflow

### ISSUE THREAD

**Issue by dennis-wey** [prefix-dev/setup-pixi#107]
When calling setup-pixi twice inside a workflow I get the following error:
 
> Run prefix-dev/setup-pixi@v0.6.0
> Downloading Pixi
>   Destination file path /home/runner/.pixi/bin/pixi already exists
>   Waiting 17 seconds before trying again
>   Destination file path /home/runner/.pixi/bin/pixi already exists
>   Waiting 12 seconds before trying again
> Error: Destination file path /home/runner/.pixi/bin/pixi already exists

I realize this can be easily bypassed, by refactoring the workflow to use the action once or using `pixi-bin-path`.
But this might be not a nice solution in a workflow that depends on several independent actions, which are all using pixi.

Therefore I would suggest:

1. Check if pixi-bin-path already exists
2. If so check if the existing pixi version is the same as in the user input
    - Only fail if the existing version does not match

**Comment by pavelzw** [comment]
In the latest version `v0.6.0`, setup-pixi skips the download when `pixi` is already on `PATH`, see https://github.com/prefix-dev/setup-pixi#self-hosted-runners
I would imagine that this already covers your use case but apparently it doesn't. Can you provide me a failing reproducible example?

**Comment by dennis-wey** [comment]
One very simple example that fails for me on a **not** self-hosted runner.
I get the same error message as above.

```
name: "2 times pixi"

on:
  push:

jobs:
  pixi:
    runs-on: ubuntu-latest
    name: Check Pixi

    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v4

      - uses: prefix-dev/setup-pixi@v0.6.0
        with:
          pixi-version: v0.20.1
          cache-write: false
          manifest-path: pyproject.toml
          auth-host: ${{ secrets.host }}
          auth-username: ${{ secrets.username }}
          auth-password: ${{ secrets.password }}

      - uses: prefix-dev/setup-pixi@v0.6.0
        with:
          pixi-version: v0.20.1
          cache-write: false
          manifest-path: pyproject.toml
          auth-host: ${{ secrets.host }}
          auth-username: ${{ secrets.username }}
          auth-password: ${{ secrets.password }}

```
