### ISSUE TITLE
How to use local relative-path PyPI dependencies with manifest in a subfolder?

### ISSUE THREAD

**Issue by jonashaag** [prefix-dev/setup-pixi#115]
I have a manifest `sub/pixi.toml`

```toml
[pypi-dependencies]
mypkg = { path = ".", editable = true }
```

If I use

```yaml
      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@...
        with:
          manifest-path: "sub/pixi.toml"
```

The `"."` editable install fails because it attempts to install from `<root>/pyproject.toml` instead of `<root>/sub/pyproject.toml`:

```
Invalid source distribution: The archive contains neither a `pyproject.toml` nor a `setup.py` file at the top level
```
