### ISSUE TITLE
Auth is not working on `ubuntu-latest`

### ISSUE THREAD

**Issue by pavelzw** [prefix-dev/setup-pixi#14]
Depends on https://github.com/prefix-dev/pixi/issues/334

```toml
[project]
name = "test-auth"
version = "0.1.0"
description = "Add a short description here"
authors = ["Pavel"]
channels = ["conda-forge", "https://repo.prefix.dev/setup-pixi-test"]
platforms = ["osx-arm64", "osx-64", "linux-64", "linux-aarch64", "win-64"]

[tasks]
test = "python -c 'print(\"Hello world!\")'"

[dependencies]
python = "3.9.*"
private-package = "*"
```

```yml
  auth-token-install:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Move pixi.toml
        run: mv test/auth/* .
      - uses: prefix-dev/setup-pixi@v0.2.0
        with:
          auth-host: https://repo.prefix.dev
          auth-token: ${{ secrets.PREFIX_DEV_TOKEN }}
      - name: Ensure private-package is installed
        run: |
          test -f .pixi/env/conda-meta/private-package-0.0.1-0.json
```

This currently doesn't work on `ubuntu-latest` because on default linux runners, there is no keychain available. pixi then default to the insecure auth method to write the credentials in `~/.rattler` but apparently they are not read.

See also #13

---

A workaround to fix this is adding the following before `uses: setup-pixi`

```yml
      - name: Unlock Keychain
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y dbus-x11 gnome-keyring
          dbus-launch --sh-syntax
          echo '' | /usr/bin/gnome-keyring-daemon --unlock
```
