### ISSUE TITLE
Possible to use with no manfiest-path file?

### ISSUE THREAD

**Issue by matthewfeickert** [prefix-dev/setup-pixi#143]
At the moment the action expects that a valid `pixi` manifest file exists either at `./` or will be provided explicitly with the `manifest-path` argument.

https://github.com/prefix-dev/setup-pixi/blob/41f1f69e78c8eb4741631c8a649ad3b63a444621/action.yml#L17-L18

Would it be possible to allow for `pixi` to be setup with no manifest file? This would provide the equivalent of

```console
$ curl -fsSL https://pixi.sh/install.sh | bash
$ . ~/.bashrc
```

The motivation would be to allow for using `pixi` to install tools in one-off workflows. This would allow replacing [something like](https://github.com/scientific-python/upload-nightly-action/blob/9d888d238eeb4b7c9eb587e3ccb24074a7bde46a/.github/workflows/ci.yml#L93-L115)

```yaml
  cleanup:
    runs-on: ubuntu-latest
    needs: [test]
    # Set required workflow secrets in the environment for additional security
    # https://github.com/scientific-python/upload-nightly-action/settings/environments
    environment:
      name: remove-old-wheels

    steps:
      - name: Install micromamba and anaconda-client
        uses: mamba-org/setup-micromamba@f8b8a1e23a26f60a44c853292711bacfd3eac822  # v1.9.0
        with:
          environment-name: remove-wheels
          create-args: >-
            python=3.12
            anaconda-client

      - name: Remove test package upload
        shell: bash -l {0}
        run: |
            anaconda --token ${{ secrets.ANACONDA_TOKEN }} remove \
              --force \
              "scientific-python-nightly-wheels/test-package"
```

with

```yaml
  cleanup:
    runs-on: ubuntu-latest
    needs: [test]
    # Set required workflow secrets in the environment for additional security
    # https://github.com/scientific-python/upload-nightly-action/settings/environments
    environment:
      name: remove-old-wheels

    steps:
      - name: Set up pixi
        uses: prefix-dev/setup-pixi@ba3bb36eb2066252b2363392b7739741bb777659  # v0.8.1
        with:
          manifest-path: false

      - name: Remove test package upload
        shell: pixi exec --spec anaconda-client -- bash -e {0}
        run: |
            anaconda --token ${{ secrets.ANACONDA_TOKEN }} remove \
              --force \
              "scientific-python-nightly-wheels/test-package"

```
