### ISSUE TITLE
`pixi-version` errors when given an actual version

### ISSUE THREAD

**Issue by Hofer-Julian** [prefix-dev/setup-pixi#15]
When trying a sightly simplified example from the README
```yaml
      - uses: prefix-dev/setup-pixi@v0.2.0
        with:
          pixi-version: "0.2.0"
          cache: true
```
I get the following error:
```
/home/runner/work/_actions/prefix-dev/setup-pixi/v0.2.0/dist/index.js:57957
    throw result.error;
    ^

ZodError: [
  {
    "validation": "regex",
    "code": "invalid_string",
    "message": "Invalid",
    "path": []
  }
]
    at get error [as error] (/home/runner/work/_actions/prefix-dev/setup-pixi/v0.2.0/dist/index.js:57858:24)
    at ZodUnion.parse (/home/runner/work/_actions/prefix-dev/setup-pixi/v0.2.0/dist/index.js:57957:18)
    at parseOrUndefined (/home/runner/work/_actions/prefix-dev/setup-pixi/v0.2.0/dist/index.js:60973:17)
    at getOptions (/home/runner/work/_actions/prefix-dev/setup-pixi/v0.2.0/dist/index.js:61050:18)
    at Object.<anonymous> (/home/runner/work/_actions/prefix-dev/setup-pixi/v0.2.0/dist/index.js:61073:15)
    at Module._compile (node:internal/modules/cjs/loader:1233:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1287:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12) {
  issues: [
    {
      validation: 'regex',
      code: 'invalid_string',
      message: 'Invalid',
      path: []
    }
  ],
  addIssue: [Function (anonymous)],
  addIssues: [Function (anonymous)],
  errors: [
    {
      validation: 'regex',
      code: 'invalid_string',
      message: 'Invalid',
      path: []
    }
  ]
}
```

Setting it to "latest" works fine so I guess something is broken with the regex:
```yaml
      - uses: prefix-dev/setup-pixi@v0.2.0
        with:
          pixi-version: latest
          cache: true
```
