### ISSUE TITLE
Example workflow does not work

### ISSUE THREAD

**Issue by tacaswell** [prefix-dev/setup-pixi#165]
Including `.` in the workflow version fails with

```
Run prefix-dev/setup-pixi@v0.8.0
2  with:
3    pixi-version: v0.39.4
4    environments: doc
5Error: Expected "=", [ \t] or [A-Za-z0-9_\-] but "." found.
```

from https://github.com/tacaswell/knots/actions/runs/12626124436/job/35178798702#step:3:6

```
      # set up pixi
      - uses: prefix-dev/setup-pixi@v0
        with:
          environments: doc

```

Is what actually worked.
