### ISSUE TITLE
disable install?

### ISSUE THREAD

**Issue by trim21** [prefix-dev/setup-pixi#178]
I only want to install pixi and install some global tools in ci, is it possible to disable `pixi install` after this action install pixi?

**Comment by pavelzw** [comment]
yes.

```yml
- uses: prefix-dev/setup-pixi@v0.8.3
  with:
    run-install: false
```

https://github.com/prefix-dev/setup-pixi/blob/92815284c57faa15cd896c4d5cfb2d59f32dc43d/action.yml#L19-L20
