### ISSUE TITLE
Action incorrectly rejects valid pyproject.toml PEP 735 dependency groups

### ISSUE THREAD

**Issue by jayqi** [prefix-dev/setup-pixi#190]
I am getting the following error using the `setup-pixi` action:

```
Error: Error while trying to read pyproject.toml file.
Error: TomlError: Inline lists must be a single type, not a mix of inline-table and string at row 56, col 10, pos 1639:
55:   { include-group = "docs" },
56>   "build",
             ^
57:   "ipython",
```

Here is my use of the action:

```
      - uses: prefix-dev/setup-pixi@v0.8.4
        with:
          pixi-version: latest
          cache: true
          cache-key: default
          environments: >-
            default
            typecheck
```

---

Here is the relevant part of my `pyproject.toml` file:

```toml
[dependency-groups]
dev = [
  { include-group = "lint" },
  { include-group = "docs" },
  "build",
  "ipython",
  "vspect",
]
docs = [
  "black",
  "markdown-callouts>=0.4.0",
  "mdx_truly_sane_lists==1.3",
  "mike",
  "mkdocs>=1.4",
  "mkdocs-jupyter",
  "mkdocs-material>=7.2.6",
  "mkdocstrings[python]>=0.19.0",
  "nbconvert>=7.7.0",
  "rich",
]
lint = [
  "ruff>=0.1.14",
]
```

Here is the [full `pyproject.toml` file](https://github.com/drivendataorg/erdantic/blob/a6574b125266b9df2dacefe719d3a0baf1bf2644/pyproject.toml).

I believe this is an incorrect rejection of a valid use of PEP 735 dependency groups. 

- This `pyproject.toml` runs without error locally and produces the environment I expect. (pixi v0.45.0)
- You can see many examples in the [official PyPA specification page for dependency groups](https://packaging.python.org/en/latest/specifications/dependency-groups/#examples) that mix inline-tables and strings when declaring dependency groups.
