### ISSUE TITLE
Issues using self-hosted runners

### ISSUE THREAD

**Issue by humphd** [prefix-dev/setup-pixi#25]
I'm having a bunch of issues running this action with a self-hosted runner.  Everything worked well until I made a change today to update some versions in `pixi.toml`.

My action basically looks like this:

```yml
env:
  PIXI_VERSION: 0.5.0

jobs:
  Lint:
    runs-on: [self-hosted, Linux, X64, ubuntu-22.04]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup pixi
      uses: prefix-dev/setup-pixi@v0.3.0
      with:
        pixi-version: v${{ env.PIXI_VERSION }}

    ...
  
  Test:
    runs-on: [self-hosted, Linux, X64, ubuntu-22.04]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Setup pixi
      uses: prefix-dev/setup-pixi@v0.3.0
      with:
        pixi-version: v${{ env.PIXI_VERSION }}

    ...
```

When I updated the `pixi.toml` and `pixi.lock`, I get errors:

```
TestENOENT: no such file or directory, lstat '.pixi'
--
TestDestination file path /home/github/.pixi/bin/pixi already exists
```

or

```
Run prefix-dev/setup-pixi@v0.3.0
Downloading Pixi
Error: Destination file path /home/github/.pixi/bin/pixi already exists
```

I've tried every combo of `post-cleanup:true`/`post-cleanup:false` based on the docs, and tried with and without `cache:true`.

I'm not sure how to fix this.  Any tips?
