### ISSUE TITLE
Updating pixi version breaks pixi install

### ISSUE THREAD

**Issue by humphd** [prefix-dev/setup-pixi#35]
I have the following workflow:

```yaml
env:
    PIXI_VERSION: 0.5.0
    ....

jobs:
    Test:
        # Use our own self-hosted runner for this
        runs-on: [self-hosted, Linux, X64, ubuntu-22.04]
        steps:
            ...
            - name: Setup pixi
              uses: prefix-dev/setup-pixi@v0.3.0
              with:
                  pixi-version: v${{ env.PIXI_VERSION }}
                  # Don't use $HOME/.pixi to work around self-runner env issues
                  # https://github.com/prefix-dev/setup-pixi/issues/25
                  pixi-bin-path: ${{ runner.temp }}/bin/pixi
                  cache: true
                  post-cleanup: true
```

I updated it to use the new release of pixi (`0.7.0`) and it breaks as follows: 

```sh
Restoring pixi cache
  Cache Size: ~108 MB (112936695 B)
  /usr/bin/tar -xf /home/github/work/_temp/1c6d344c-c994-48ee-aa1b-cc8e0f6be174/cache.tzst -P -C /home/github/work/Project/Project --use-compress-program unzstd
  Received 112936695 of 112936695 (100.0%), 107.7 MBs/sec
  Cache restored successfully
  Restored cache with key `pixi-linux-64-374cf0d4d1aa8b897059fc7d641107d070f1dafa01ec8a5d5ceeefe4f4f9adb1`
/home/github/work/_temp/bin/pixi install --locked --manifest-path pixi.toml
  × the project location seems to be change from `/home/runner/work/
  │ Project/Project/.pixi` to `/mnt/github/work/Project/
  │ Project/.pixi`, this is not allowed.
  │ Please remove the `.pixi` folder and run again
```
