### ISSUE TITLE
Matrix testing

### ISSUE THREAD

**Issue by hadim** [prefix-dev/setup-pixi#48]
I am experimenting using pixi and its GH Actions to replace my `micromamba` workflow.

Currently my CI looks like:

```yaml
      - name: Setup mamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: env.yml
          environment-name: my_env
          cache-environment: true
          cache-downloads: true
          create-args: >-
            python=${{ matrix.python-version }}
            rdkit=${{ matrix.rdkit-version }}
```

I am wondering whether something similar is possible with `prefix-dev/setup-pixi`?
