### ISSUE TITLE
Pixi location change breaks self-hosted runner

### ISSUE THREAD

**Issue by humphd** [prefix-dev/setup-pixi#66]
Today I updated our `main` branch to use pixi v0.12.0 and setup-pixi to v0.4.1.  After this, I continued work on another branch, which was behind `main`, and my CI jobs fail as follows:

```sh
Prepare all required actions
Getting action download info
Download action repository 'prefix-dev/setup-pixi@v0.4.1' (SHA:ccc5c07ed948b849df4b[3](https://github.com/DeepStructure-io/DeepStructure/actions/runs/7560629057/job/20587085983#step:4:3)578d785f3afd7[4](https://github.com/DeepStructure-io/DeepStructure/actions/runs/7560629057/job/20587085983#step:4:4)65c67)
Run ./.github/actions/pixi-setup
Run prefix-dev/setup-pixi@v0.4.1
Downloading Pixi
Restoring pixi cache
/home/github/work/_temp/bin/pixi install --locked --manifest-path pixi.toml
  × the project location seems to be change from `/home/runner/work/
  │ DeepStructure/DeepStructure/.pixi` to `/home/github/work/DeepStructure/
  │ DeepStructure/.pixi`, this is not allowed.
  │ Please remove the `.pixi` folder and run again

Error: The process '/home/github/work/_temp/bin/pixi' failed with exit code 1
```

We are using a self-hosted runner for our CI/CD jobs.  I had a similar issue in the past with cache on self-hosted runners when upgrading (#25), but this seems slightly different.

**Comment by humphd** [comment]
NOTE: rebasing the other branch didn't help this.  Do I need to manually intervene on the self-hosted runner?

**Comment by wolfv** [comment]
Maybe you could change the cache key so that the cache is busted?

**Comment by humphd** [comment]
My action for setting this up looks like this:

```yml
        - name: Setup pixi
          uses: prefix-dev/setup-pixi@v0.4.1
          with:
              pixi-version: v0.12.0
              # Don't use $HOME/.pixi to work around self-runner env issues
              # https://github.com/prefix-dev/setup-pixi/issues/25
              pixi-bin-path: ${{ runner.temp }}/bin/pixi
              post-cleanup: true
              cache: true
```

I'm not sure how I'd change the cache key.  Should I disable cache for now?
