### ISSUE TITLE
Custom shell wrapper doesn't work with powershell

### ISSUE THREAD

**Issue by melund** [prefix-dev/setup-pixi#78]
When using the custom shell wrapper with powershell I get an error from github actions: 

I am doing something like this on Windows runner. 
```
- run:
    pytest 
  shell: pixi run pwsh -e test {0}
```

![image](https://github.com/prefix-dev/setup-pixi/assets/1038978/1cd67237-a00d-466d-b97a-160701bac031)

**Comment by ruben-arts** [comment]
The pixi run command sends all info after the initial command to the task. 
I think something like this could work:
```yaml
- name: Run test with powershell
  run: pytest
  shell: pixi run  -e test pwsh -File {0}
```

**Comment by pavelzw** [comment]
This should be updated in the readme (and we should add a test for it as well)

**Comment by pavelzw** [comment]
maybe also add a test for cmd.exe

**Comment by melund** [comment]
@ruben-arts 

> I think something like this could work:
> `shell: pixi run -e test pwsh -File {0}`

It doesn't seem to work. 

![image](https://github.com/prefix-dev/setup-pixi/assets/1038978/5955c80b-862d-4f63-8d14-75aebb697ffa)

It is odd, because [GitHub Actions Docs](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#custom-shell) does seem to indicate that is possible. Maybe they do something special if they detect the first argument is "pwsh" or "powershell".

**Comment by ruben-arts** [comment]
Yeah I experienced the same, that's why we added this to the documentation and tests in #79 
```yml
- run: |
    python --version | Select-String "3.11"
  shell: pixi run pwsh -Command {0}
```

You can use the environment with:
```yml
- run: pytest
  shell: pixi run -e test pwsh -Command {0}
```
