### ISSUE TITLE
Restoring cache fails with pyproject.toml

### ISSUE THREAD

**Issue by garymm** [prefix-dev/setup-pixi#93]
Say my repo is named `foo`, and inside the repo I have another directory named `foo`.
At the root of the repo I have a `pyproject.toml` file that contains:

```toml
[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "foo"
requires-python = ">=3.10"
dynamic = ["version"]

[tool.pixi.project]
name = "foo"
channels = ["conda-forge"]

[tool.pixi.pypi-dependencies]
foo = { path = "./", editable = true }
```

When I use the setup-pixi action version 0.5.1 it fails:
```
Restoring pixi cache
Error: Failed to generate cache key: Error: ENOENT: no such file or directory, open '/home/runner/work/foo/foo/pyproject.lock'
```

GitHub job:
```yaml
jobs:
  pytest:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.5.1
        with:
          manifest-path: pyproject.toml
          pixi-version: v0.18.0
          cache: true
          cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
      - name: pytest
        run: pixi run pytest --capture=no --verbose
```
